name: glass_calendar_pro
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Các thư viện đã sử dụng trong code main.dart
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  vnlunar: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.0.0
  timezone: ^0.9.2 # Hỗ trợ tính toán múi giờ cho thông báo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # Thêm dòng này

# Thêm cấu hình này ở cuối file (cùng cấp với flutter:)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Đường dẫn tới file ảnh bạn vừa upload
  min_sdk_android: 21 # Quan trọng để hỗ trợ các máy đời mới
  
  # Cấu hình icon launcher (nếu có file ảnh)
  # assets:
  #   - images/